### ISSUE TITLE
 when use runTSNE and PlotByDatasetandCluster the data did't cluster 

### ISSUE THREAD

**Issue by lexie-lee** [welch-lab/liger#149]
hi,
   I met some troubles when I use liger. My data processed successfully in Seurat, and grouped in Seurat. I use 'SeuratToLiger'  changed the Data type successfully and the dataset is as I want. but when I follow the examples in vignette "walkthrough-aligning PBMC data", I ran 'normalize' 'selectGenes' 'scaleNotCenter' 'suggestK' 'optimizeALS' 'runSTNE' 'plotByDatasetAndCluster' one by one, but the plots shows  the points are everywhere, there are  not three clusters, however,the plots looks like figure2 rather figure1 in "walkthrough". I don't know why. cause it's really easy steps. And if I reserve the tsne.coordinate processed by Seurat, it works.  so should I just keep the Seurat tSNE results?   can you give me some advice?

**Comment by jw156605** [comment]
What `k` did you use for your analysis?
