### ISSUE TITLE
plotGene issue Error in `.rowNamesDF<-`(x, value = value) 

### ISSUE THREAD

**Issue by Timothy-WANG** [welch-lab/liger#170]
Hi, Thanks for developing the great tools liger. Here is an issue. When I want to hight the genes after I have integrated the data, it just come out the following errors. Thanks for your attention. Tim

> plotGene(all.pbmc, "gene1")
Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length

**Comment by skpalan** [comment]
Hi Tim, can you check whether this gene is in your `liger` object? For example, if you have 2 datasets stored in your object, you can use these codes to check:
```
"gene1" %in% rownames(all.pbmc@norm.data[[1]])
"gene1" %in% rownames(all.pbmc@norm.data[[2]])
```
Also it would be better if you can provide some of your system information like the outputs of `sessioninfo()`.
