### ISSUE TITLE
bed file format for ATAC-seq integration

### ISSUE THREAD

**Issue by PeterZZQ** [welch-lab/liger#184]
Hi,

I just tried to run through your scATAC-seq and scRNA-seq integration manuscript. Can you pls provide the hg19_genes.bed and hg19_promoters.bed file. I downloaded the hg19_genes file from BioMart and generate the bed file as **chrx-start-end** form, and generate promoter using 3000bp upstream, i.e. **chrx-(start-3000)-start**, but after going through the pipeline, I only have 4 columns, which is basically like this:
<img width="983" alt="image" src="https://user-images.githubusercontent.com/37580703/92318025-b9f27000-efd4-11ea-8808-c65c8160743d.png">
And then I run into error when applying **makeFeatureMatrix** function, since I don't have column 7.

**Comment by skpalan** [comment]
Hi, the index files should contain 6 columns. For details, you can refer to the actual files (hg19_genes.bed and hg19_promoters.bed) we used in the tutorial [here](https://umich.box.com/s/wip2nzpktn6fdnlpc83o1u7anjn4ue2c).
