### ISSUE TITLE
hg19_genes.bed and hg19_promoters.bed files

### ISSUE THREAD

**Issue by arutik** [welch-lab/liger#185]
Hi,

Not sure if this has been raised already, but how does one get the `hg19_genes.bed` and `hg19_promoters.bed` files? Also I would like to use similar files for hg38 genome but again not sure how to produce them / where to get them, and your tutorial on scRNA-scATAC integration doesn't explicitly state that.

Thank you,
Anna Arutyunyan

**Comment by skpalan** [comment]
Hi, The gene coordinate file was downloaded from UCSC database and we made the promoter file by taking the upstream 3kb of each gene transcription start site. You can basically do the same for hg38 genome.

**Comment by arutik** [comment]
Hi,

Thank you, and can you please provide the exact command that you used to produce the promoters file and a link to the genes file?

**Comment by Jeff1995** [comment]
> Hi, The gene coordinate file was downloaded from UCSC database and we made the promoter file by taking the upstream 3kb of each gene transcription start site. You can basically do the same for hg38 genome. We also require these files to have 6 columns, for details, you can refer to the actual bed files (hg19_genes.bed and hg19_promoters.bed) we used in the tutorial [here](https://umich.box.com/s/wip2nzpktn6fdnlpc83o1u7anjn4ue2c).

The URL for the bed files seems to have expired?

**Comment by skpalan** [comment]
Hi Zhijie, we have updated the link to the all example data, please take a look and feel free to message us if you have any other issues.

**Comment by chengmingbo** [comment]
Hi, I generated the files using R, please let me if there's any issue.
```r
library(stringr)
library(magrittr)
library(Matrix)
library(tidyverse)
library(dplyr)
library(GenomeInfoDb)
library(org.Hs.eg.db)
library(EnsDb.Hsapiens.v86)
library(TxDb.Hsapiens.UCSC.hg38.knownGene)


dir.create("save")


gene.coords <- genes(EnsDb.Hsapiens.v86, filter = ~ gene_biotype == "protein_coding")
df <- data.frame(seqnames=seqnames(gene.coords),
    starts=start(gene.coords)-1,
    ends=end(gene.coords),
    names=elementMetadata(gene.coords)$symbol,
    scores=".",
    strands=strand(gene.coords)

    )   


dff <- df %>% arrange(seqnames, starts, ends)
dff$seqnames <- paste0("chr", dff$seqnames)
write.table(dff, "save/hg38_genes.bed", sep="\t", col.names=F, row.names=F, quote=F)

TSS <- unique(resize(GenomicFeatures::transcripts(TxDb.Hsapiens.UCSC.hg38.knownGene, columns=c("GENEID")),
                     width = 1, fix = "start"))
TSS <- GenomeInfoDb::keepStandardChromosomes(TSS, pruning.mode = "coarse")

mcols(TSS)$GENEID <-as.numeric(mcols(TSS)$GENEID)
TSS <- TSS[!is.na(TSS$GENEID), ]

mcols(TSS)$GENEID <-as.character(mcols(TSS)$GENEID)
mcols(TSS)$symbol <- AnnotationDbi::mapIds(org.Hs.eg.db,
                                           keys = mcols(TSS)$GENEID,
                                           column = "SYMBOL",
                                           keytype = "ENTREZID",
                                           multiVals = "first")

TSS  <- TSS[!is.na(mcols(TSS)$symbol), ]
TSS <- TSS[mcols(TSS)$symbol %in% dff$names, ]


df_TSS <- as.tibble(TSS)
df_TSS <- df_TSS%>% arrange(seqnames, start, end)
df_TSS <- df_TSS[!duplicated(df_TSS$symbol), ]
write.table(df_TSS, "save/hg38_tss.bed", sep="\t", col.names=F, row.names=F, quote=F)

gr_promoter <- makeGRangesFromDataFrame(df_TSS, keep.extra.columns=T)
df_promoter <- as.tibble(promoters(gr_promoter, upstream = 3000, downstream = 0)) 
df_promoter <- df_promoter[, c("seqnames", "start", "end", "symbol", "width", "strand")]
df_promoter$width <- "." 

write.table(df_promoter, "save/hg38_promoter.bed", sep="\t", col.names=F, row.names=F, quote=F)
```
