### ISSUE TITLE
Liger optimizeALS function - Select k lower than the number of cells in smallest dataset: 0

### ISSUE THREAD

**Issue by strawberry789** [welch-lab/liger#196]
Hello,

I converted my Seurat objects (scRNA + scATAC) to a Liger object using the "seuratToLiger" function:

data <- list(atac, rna)
object <- seuratToLiger(data)

Then, I proceeded with

object <- normalize(object)
object <- selectGenes(object, datasets.use = 2)
object <- scaleNotCenter(object)

which gave this output 

[1] "Removing 2647 genes not expressing in ATAC."
[1] "Removing 3337 genes not expressing in SeuratProject."

Then,

object <- optimizeALS(object, k = 20)

gives the following error:

Error in optimizeALS.list(object = object@scale.data, k = k, lambda = lambda, : Select k lower than the number of cells in smallest dataset: 0

But my Liger object shows 5984 cells in 2 datasets (scRNA+scATAC)

How should I go about this error?  Thank you.

**Comment by CSQxiaogongju** [comment]
Hello~I also encountered the same problem, did you solve this problem?

**Comment by CSQxiaogongju** [comment]
> Hello,
> 
> I converted my Seurat objects (scRNA + scATAC) to a Liger object using the "seuratToLiger" function:
> 
> data <- list(atac, rna) object <- seuratToLiger(data)
> 
> Then, I proceeded with
> 
> object <- normalize(object) object <- selectGenes(object, datasets.use = 2) object <- scaleNotCenter(object)
> 
> which gave this output
> 
> [1] "Removing 2647 genes not expressing in ATAC." [1] "Removing 3337 genes not expressing in SeuratProject."
> 
> Then,
> 
> object <- optimizeALS(object, k = 20)
> 
> gives the following error:
> 
> Error in optimizeALS.list(object = [object@scale.data](mailto:object@scale.data), k = k, lambda = lambda, : Select k lower than the number of cells in smallest dataset: 0
> 
> But my Liger object shows 5984 cells in 2 datasets (scRNA+scATAC)
> 
> How should I go about this error? Thank you.

Hello~I also encountered the same problem, did you solve this problem?

**Comment by cgao90** [comment]
Hi, the error message indicates that the smaller dataset has cells fewer than `k` (20 in this example). It's worth checking the number of cells (rows) in each scaled dataset.

**Comment by cgao90** [comment]
We replaced `quantileAlignSNF` by `quantile_norm`. Did you happen to call `suggestLambda`?

**Comment by CSQxiaogongju** [comment]
> We replaced `quantileAlignSNF` by `quantile_norm`. Did you happen to call `suggestLambda`?
Here is my code, where osmFISH is the spatial transcription dataset and Zeisel is the scRNA-seq dataset. The rows of the matrix are genes and the columns are cells. if I call "suggestLambda" function before optimizeALS function, I will have the following error. if I not call "suggestLambda" function before optimizeALS function, I will have the above error.  I am very confused, how can I solve this bug. I look forward to your reply.
<img width="495" alt="8E0F5EE820350BB6B76C20195B40C05F" src="https://user-images.githubusercontent.com/44634634/210941350-46eddde4-e6b5-414c-ab1c-f197a6661930.png">
<img width="176" alt="0255734B95E54463AF1C1A2F5DFCDE23" src="https://user-images.githubusercontent.com/44634634/210941387-0c7760df-69a9-4f98-b998-deb48d880794.png">

<img width="708" alt="E6A9CF65A1A1147C156FA41584102987" src="https://user-images.githubusercontent.com/44634634/210945017-b54df28e-506e-4b1f-82ff-e245bcf65230.png">

**Comment by cgao90** [comment]
According to your code and the output, Zeisel data originally contains 1691 cells, all of which got removed during the preprocessing steps as they have 0 count. Are genes from `Gene_set` included in both datasets?

**Comment by CSQxiaogongju** [comment]
> According to your code and the output, Zeisel data originally contains 1691 cells, all of which got removed during the preprocessing steps as they have 0 count. Are genes from `Gene_set` included in both datasets?

Yes~they are included in both datasets.
Gene_set <- intersect(rownames(osmFISH),rownames(Zeisel))

**Comment by CSQxiaogongju** [comment]
> > According to your code and the output, Zeisel data originally contains 1691 cells, all of which got removed during the preprocessing steps as they have 0 count. Are genes from `Gene_set` included in both datasets?
> 
> Yes~they are included in both datasets. Gene_set <- intersect(rownames(osmFISH),rownames(Zeisel))

What can I do to avoid all cells in the Zeisel data being deleted?

**Comment by CSQxiaogongju** [comment]
what can I do to avoid removing all cells in the Zeisel dataset?

**Comment by cgao90** [comment]
You might wanna check the dimension of the datasets in Ligerex@raw.data, Ligerex@norm.data and Ligerex@scale.data first to see at which step the cells got removed. 
Also, lambda = 5 (for `optimizeALS`) should work for most of the cases.

**Comment by CSQxiaogongju** [comment]
I have checked the dimension of the datasets in Ligerex@raw.data, Ligerex@norm.data.  The normalization step removes all cells in the scRNA-seq data. I check the parameter "remove.missing" in the normalize function, but it only removes cells not expressing any measured genes. My scRNA-seq data contains cells with expressed genes.
<img width="608" alt="DC528DA6486E72105C3400BA4458C7F7" src="https://user-images.githubusercontent.com/44634634/211139344-b1541aab-f6ec-4aff-b5b1-5ddb2d6fb55d.png">

<img width="616" alt="D5A7DCD20A2988879C7E5B11F4C3815F" src="https://user-images.githubusercontent.com/44634634/211139355-dd8ba374-2d16-42e0-ac2b-57a28ab51b98.png">

<img width="795" alt="BCF6144CB93EC5284FE3B0FC56189EF1" src="https://user-images.githubusercontent.com/44634634/211139366-81dbd4eb-ea3d-419a-8adf-633713828fae.png">


<img width="795" alt="BCF6144CB93EC5284FE3B0FC56189EF1" src="https://user-images.githubusercontent.com/44634634/211139360-292658c3-0d07-4129-8e1c-3341ba2f8fe8.png">

**Comment by CSQxiaogongju** [comment]
I have checked the dimension of the datasets in Ligerex@raw.data, Ligerex@norm.data. The normalization step removes all cells in the scRNA-seq data. I check the parameter "remove.missing" in the normalize function, but it only removes cells not expressing any measured genes. My scRNA-seq data contains cells with expressed genes.
<img width="406" alt="AD34AEE3B3BFCC
![F753A8ECD4E2A7D24B525B7A4A830970](https://user-images.githubusercontent.com/44634634/211139819-e73e2bd9-82b5-41a6-b29a-3da9b58bb6fa.jpg)
4B3A5ACEAB9380F4BC" src="https://user-images.githubusercontent.com/44634634/211139797-81c86c3a-1949-4253-b5c3-e78720b11af4.png">

**Comment by CSQxiaogongju** [comment]
![F753A8ECD4E2A7D24B525B7A4A830970](https://user-images.githubusercontent.com/44634634/211139847-cc93ecc3-7542-4278-ae83-aeea715ea868.jpg)

**Comment by CSQxiaogongju** [comment]
Hi~chao gao, I found that if there are cells removed in the preprocessing step, then will be a subscript out of bounds problem when running the “imputeKNN” function. Is it caused by the inconsistency of the dimensions of the Ligerex@raw.data, Ligerex@norm.data, and Ligerex@scale.data?
![Uploading 07D053F34
<img width="943" alt="07D053F34E3CE1222180ACFA5368CD56" src="https://user-images.githubusercontent.com/44634634/211159119-dab7af07-4ad8-4b4b-948b-9fc3326573ac.png">
E3CE1222180ACFA5368CD56.png…]()

**Comment by CSQxiaogongju** [comment]
<img width="943" alt="07D053F34E3CE1222180ACFA5368CD56" src="https://user-images.githubusercontent.com/44634634/211159163-bb7ee43f-b05e-4733-bcfd-5b6e3080609b.png">

**Comment by cgao90** [comment]
In order to figure out why all of the cell in the 2nd dataset got removed , you could first do a quick sanity check by calculating the column sum of your original input, ligerex@raw.data[2] and investigating if those cells indeed have 0 counts.
