### ISSUE TITLE
Merge datasets on marker plots

### ISSUE THREAD

**Issue by alexisweber** [welch-lab/liger#198]
the plotGene() function will return two plots, one plot for expression of the selected gene in one dataset and one plot for expression of the gene in the other dataset. Is there any way to merge this in the same plot to view expression of the gene across integrated datasets?

Thanks in advance

**Comment by samuel-marsh** [comment]
Hi,

To return single plot with entire object you just need to specify "none" for the `plot.by` parameter in `plotGene`.
i.e.
```
plotGene(liger_obj, gene = "GENE_NAME", plot.by = "none")
```

Best,
Sam
