### ISSUE TITLE
Online branch -- Missing_gene removal

### ISSUE THREAD

**Issue by JZL** [welch-lab/liger#199]
Hi,

I was working with the `online` branch and comparing it to the master branch and found that `selectGenes` gave pretty different results (at the same threshold, same underlying data) - 2,295 genes for master (in ram), 24,308 with h5.

Tracing it upwards through the code, I think I narrowed it down to the master version which [removes all `missing_genes`](https://github.com/welch-lab/liger/blob/718fc0e47d5a85e4763cc63a139e3f5792b72e02/R/liger.R#L514)= all-zero genes across replicates within each dataset. The h5 version of `createLiger` exits beforehand.

To make sure this was the root cause, I created alternate versions of my input 10X h5 files which just had the missing_genes removed and then it gives all identical variable genes results to the master results.

I can attach my code but it requires two passes to not read everything into memory at one time, because it first needs to intersect the missing genes of each h5 file, then go back and remove them from each h5 file. There might be a more clever one-pass solution which creates an analogous `gene_sums` h5 group at the same time as it creates the `cell_sums` in `normalize` (especially because we don't really need the gene_sums, just whether it's always 0 or not). I'm happy to work with you on any improvements or any other ideas if you ran into similar problems in the past!

Thanks
Jonah

**Comment by MacoskoLab** [comment]
Hi Jonah,

It is true that, unlike in-memory liger, online Liger does not have the option to remove the missing genes at this moment. By setting `remove.missing = F` for in-memory liger, they would produce the same set of selected genes. It would be great if we can incorporate this functionality into the online liger. We can think more about this potential improvement. 

Best,
Chao

**Comment by cgao90** [comment]
Hi Jonah,

It is true that the online liger does not have the option to remove the missing genes at this moment. By setting `remove.missing = F` for the in-memory version when creating the object, they would produce the same set of selected genes. It would be great if we can incorporate this functionality into online liger. We can think about about this potential improvement.

Best,
Chao
