### ISSUE TITLE
Version numbering

### ISSUE THREAD

**Issue by samuel-marsh** [welch-lab/liger#203]
Hi Liger Team,

Just wondering whether you guys could please update the software version number when major changes or bug fixes are pushed (i.e. the recent merge of online branch with master).  All the needs to be changed is the version number in the Description file so that when pulled from Github it shows as different version in R.  Liger has remained at 0.5.0 for while so harder to keep track of what changes are present in an installed version vs. latest changes/fixes.

Also while I understand you may not want to make such large change but if the version number was increased above the version # of the other ["liger" package on CRAN](https://cran.r-project.org/web/packages/liger/index.html) then it would avoid issue that I think number of people have which is that if you run update packages in R when it sees this liger package R it assumes it is CRAN package because of name collision and overwrites it because it thinks the CRAN liger package is newer version than the current version of this liger package.  So if liger version was increased to something greater than current CRAN package (1. 1.2) it would circumvent this sometimes confusing issue.

Thanks!!
Sam

**Comment by cgao90** [comment]
Hi Sam,

Thanks very much for raising this issue. Currently we are working on some minor modifications on Liger so that it can be published on CRAN. Once it is all set we will update the version number.

Best,
Chao

**Comment by samuel-marsh** [comment]
Hi Chao,

Awesome, sounds good!

Thanks,
Sam

**Comment by samuel-marsh** [comment]
Hi Chao and Team,

Just reviving this issue with request to update version numbers as fixes are pushed to branch.  It makes it difficult to assess which version is installed (CRAN or github development version) when the installed version numbers are identical between the two.

Best,
SAm

**Comment by samuel-marsh** [comment]
Actually seeing version on master is now 1.0 vs. rliger branch 0.5.0.  But still would be helpful with subsequent fixes pushed to master to incrementally update version number in Description file to facilitate easy identification of version installed.

Thanks,
Sam

**Comment by cgao90** [comment]
Hi Sam, 

Totally agree with you. Also, next time we publish the latest version on CRAN, the version number of rliger branch (consistent with one on CRAN) will be updated accordingly.

Best,
Chao

**Comment by samuel-marsh** [comment]
Sounds good thanks!!!
