### ISSUE TITLE
Is it possible to annotate different cell clusters using liger?

### ISSUE THREAD

**Issue by hugo-username** [welch-lab/liger#205]
I am new to R, and I practice analyzing scRNA seq data using liger. I have done UMAP on my cells and they are clustered into 15 subsets with different marker genes. I wonder if I can annotate each clusters with their markers with liger. If not, how can I export the marker gene data and annotate them by other packages.
Thanks.

**Comment by skpalan** [comment]
Hi, while LIGER is able to give the top marker genes for each of the clusters, it cannot annotate the clusters automatically. There might be some packages that can do automatically annotation, but people usually annotate clusters by hand based on biological experience and marker gene expression to give the most accurate and credible results.

If you would like to do hand annotation, I would suggest using function `runWilcoxon` at the first step to identify markers for each of the cluster, and then use `plotGene` to check their expression. If you only want the marker genes, `runWilcoxon` returns a `data.frame` object that contain everything include the gene symbols and all the statistics. You can then extract or filter any information you are interested in.

**Comment by hugo-username** [comment]
> Hi, while LIGER is able to give the top marker genes for each of the clusters, it cannot annotate the clusters automatically. There might be some packages that can do automatically annotation, but people usually annotate clusters by hand based on biological experience and marker gene expression to give the most accurate and credible results.
> 
> If you would like to do hand annotation, I would suggest using function `runWilcoxon` at the first step to identify markers for each of the cluster, and then use `plotGene` to check their expression. If you only want the marker genes, `runWilcoxon` returns a `data.frame` object that contain everything include the gene symbols and all the statistics. You can then extract or filter any information you are interested in.

Thanks for your reply.
