### ISSUE TITLE
Removing dimensions for mitochondrial content.

### ISSUE THREAD

**Issue by stemangiola** [welch-lab/liger#206]
Hello, thanks for the tool!

With this dimensionality reduction

```r
cancer_lymphoid %>%
	NormalizeData() %>%
	FindVariableFeatures() %>%
	ScaleData(split.by = "sample", do.center = FALSE) %>%
	SeuratWrappers::RunOptimizeALS(k = 20, lambda = 5, split.by = "sample") %>%
	SeuratWrappers::RunQuantileNorm(split.by = "sample")
```

I obtain cell clusters that include mitochondrial genes as markers

![image](https://user-images.githubusercontent.com/7232890/107609679-c79ed680-6c93-11eb-9be0-fce88e633dad.png)

But if I look for dimensions that are associated with mitochondrial proportion, I don't see strong correlations. 

![image](https://user-images.githubusercontent.com/7232890/107609444-08e2b680-6c93-11eb-8d5b-b9470fdd4f56.png)

Should I look to linear relationships? Or in some other way?

____________________________

Also, if I look relations with the cell library size (since is not possible to regress variables directly), I see a lot of small associations.

![image](https://user-images.githubusercontent.com/7232890/107609548-5ced9b00-6c93-11eb-95f3-13f3b81f118e.png)

I am a bit confused. I would like to use liger, however I need to regress our mitochondrial content and library size.

Thanks a lot.

@jw156605  I want to make sure I am doing the right thing in relation with https://github.com/welch-lab/liger/issues/113

**Comment by jw156605** [comment]
The genes you highlighted are ribosomal proteins, not mitochondrial genes. Ribosomal proteins can also be related to technical artifacts, though.

**Comment by VirginiaCora** [comment]
Hello,
Thank you for developing LIGER! In my LIGER corrected data I also have one cluster with mitochondrial genes as top markers so I reopened this thread to ask more information on how to judge which factors to regress out during the quantile normalisation step (like discussed in #113 ). What exactly should I plot against the variable to regress out, like was done here by @stemangiola? Are the pure values of the H.norm slot? And then, is it enough to check for linear relationships to spot the factors containing the technical signal to exclude, like was written in this thread? 

Thank you already for your time!
