### ISSUE TITLE
UINMF while loop error on own data

### ISSUE THREAD

**Issue by shazanfar** [welch-lab/liger#213]
Hi there,

Thanks for your work on developing the UINMF approach for disjoint features. I am able to follow the vignette with the example data provided, but run into errors when I use my own example data. I've included the dropbox link for the toy input data I'm using, and the code output I get, below. Can you help me understand why this error occurs with my input data, and what steps should be taken to address it?

Thanks so much

Cheers,
Shila

`> counts_list = readRDS(file = url("https://www.dropbox.com/s/0msytqp9mp8q475/counts_list.Rds?raw=1"))`
`> `
`> # two matrices`
`> lapply(counts_list, dim)`
`$X`
`[1] 10000  3611`
``
`$Y`
`[1] 5000 6460`
``
`> `
`> # create liger object`
`> data_liger = createLiger(counts_list)`
`[1] "Removing 3462 genes not expressed in X."`
`[1] "Removing 1582 genes not expressed in Y."`
`> `
`> # normalise the data`
`> data_liger <- liger::normalize(data_liger)`
`> `
`> # select features from the unshared set, from all data modalities`
`> # using parameter from vignette`
`> data_liger <- selectGenes(data_liger, unshared = TRUE, `
`+                           unshared.datasets = as.list(seq_len(length(counts_list))),`
`+                           unshared.thresh = 0.4)`
`[1] "Selected 274 unshared features from X Dataset"`
`[1] "Selected 142 unshared features from Y Dataset"`
`> `
`> # rescale the data`
`> data_liger <- scaleNotCenter(data_liger)`
`[1] "Removing 368 genes not expressed in X."`
`[1] "Removing 460 genes not expressed in Y."`
`> `
`> # perform the UINMF, using parameters from vignette`
`> data_liger <- optimizeALS(data_liger, k=30, use.unshared = TRUE)`
`[1] "Performing Factorization using UINMF"`
`[1] "Processing"`
`  |======                                                                                       |   7%Error in while (delta > thresh & iter <= max.iters) { : `
`  missing value where TRUE/FALSE needed`
`> `
`> # different error with max.iters = 1`
`> data_liger <- optimizeALS(data_liger, k=30, use.unshared = TRUE, max.iters = 1)`
`[1] "Performing Factorization using UINMF"`
`[1] "Processing"`
`  |=============================================================================================| 100%`
`Current seed  1  current objective  NaNError in if (obj_train < best_obj) { : `
`  missing value where TRUE/FALSE needed`
`> `
`> sessionInfo()`
`R version 4.0.5 (2021-03-31)`
`Platform: x86_64-apple-darwin19.6.0 (64-bit)`
`Running under: macOS Catalina 10.15.7`
``
`Matrix products: default`
`BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib`
`LAPACK: /usr/local/Cellar/r/4.0.5/lib/R/lib/libRlapack.dylib`
``
`locale:`
`[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8`
``
`attached base packages:`
`[1] parallel  stats4    stats     graphics  grDevices utils     datasets  methods   base     `
``
`other attached packages:`
` [1] SingleCellExperiment_1.12.0 SummarizedExperiment_1.20.0 Biobase_2.50.0             `
` [4] GenomicRanges_1.42.0        GenomeInfoDb_1.26.7         IRanges_2.24.1             `
` [7] S4Vectors_0.28.1            BiocGenerics_0.36.1         MatrixGenerics_1.2.1       `
`[10] matrixStats_0.58.0          liger_0.5.0                 patchwork_1.1.1            `
`[13] Matrix_1.3-2                cowplot_1.1.1               devtools_2.4.0             `
`[16] usethis_2.0.1              `
``
`loaded via a namespace (and not attached):`
`[1] bitops_1.0-6              fs_1.5.0                  bit64_4.0.5`
` [4] RColorBrewer_1.1-2        rprojroot_2.0.2           tools_4.0.5              `
` [7] utf8_1.2.1                R6_2.5.0                  irlba_2.3.3              `
`[10] ResidualMatrix_1.0.0      DBI_1.1.1                 colorspace_2.0-0         `
`[13] withr_2.4.2               tidyselect_1.1.0          prettyunits_1.1.1        `
`[16] processx_3.5.1            bit_4.0.4                 curl_4.3                 `
`[19] compiler_4.0.5            cli_2.4.0                 BiocNeighbors_1.8.2      `
`[22] hdf5r_1.3.3               desc_1.3.0                DelayedArray_0.16.3      `
`[25] SpatialUtils_0.1.0        scales_1.1.1              callr_3.7.0              `
`[28] digest_0.6.27             rmarkdown_2.7             XVector_0.30.0           `
`[31] htmltools_0.5.1.1         pkgconfig_2.0.3           sessioninfo_1.1.1        `
`[34] sparseMatrixStats_1.2.1   highr_0.9                 fastmap_1.1.0            `
`[37] rlang_0.4.10              rstudioapi_0.13           FNN_1.1.3                `
`[40] DelayedMatrixStats_1.12.3 generics_0.1.0            riverplot_0.10           `
`[43] mclust_5.4.7              ica_1.0-2                 BiocParallel_1.24.1      `
`[46] dplyr_1.0.5               RCurl_1.98-1.3            magrittr_2.0.1           `
`[49] BiocSingular_1.6.0        GenomeInfoDbData_1.2.4    scuttle_1.0.4            `
`[52] Rcpp_1.0.6                munsell_0.5.0             fansi_0.4.2              `
`[55] lifecycle_1.0.0           zlibbioc_1.36.0           plyr_1.8.6               `
`[58] Rtsne_0.15                pkgbuild_1.2.0            grid_4.0.5               `
`[61] ggrepel_0.9.1             crayon_1.4.1              doSNOW_1.0.19            `
`[64] lattice_0.20-41           beachmat_2.6.4            knitr_1.32               `
`[67] ps_1.6.0                  pillar_1.6.0              igraph_1.2.6             `
`[70] codetools_0.2-18          pkgload_1.2.1             glue_1.4.2               `
`[73] evaluate_0.14             remotes_2.3.0             vctrs_0.3.7              `
`[76] batchelor_1.6.3           foreach_1.5.1             testthat_3.0.2           `
`[79] RANN_2.6.1                gtable_0.3.0              purrr_0.3.4              `
`[82] assertthat_0.2.1          cachem_1.0.4              ggplot2_3.3.3            `
`[85] xfun_0.22                 rsvd_1.0.5                tibble_3.1.1             `
`[88] snow_0.4-3                iterators_1.0.13          tinytex_0.31             `
`[91] memoise_2.0.0             ellipsis_0.3.1           `

**Comment by Akriebs** [comment]
Hi Shila,
Thanks for bringing this issue to our attention, as well as for providing your data for testing. I believe we have resolved the issue, and I have successfully run your data example without error. Please redownload the updated U-algorithm branch, and let us know if you encounter any further issues. 
Thank you for your patience!
April

**Comment by shazanfar** [comment]
Thanks April,

I'm encountering a download/build issue with the updated package on Mac (works fine on linux), could you check this please?

Thanks again!

Cheers,
Shila

> install_github("welch-lab/liger", ref = "U_algorithm", force = TRUE)
Downloading GitHub repo welch-lab/liger@U_algorithm
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/welch-lab/liger/tarball/U_algorithm' failed

(asked another person to install and their error message below)
   13 errors generated.
   make: *** [ModularityOptimizer.o] Error 1
   ERROR: compilation failed for package 'liger'
─  removing '/private/var/folders/lf/cjtf6ppx32b28hyzg6dgfnw1h6d7q3/T/RtmpCtvfyY/Rinst14ea3c8c2a63/liger'
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'liger' from GitHub:
  System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
E>       ~~^
E> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:329:9: error: no member named 'isunordered' in the global namespace
E> using ::isunordered;
E>       ~~^
E> 13 errors generated.
E> make: *** [ModularityOptimizer.o] Error 1
E> ERROR: compilation failed for package 'liger'
E> * removing '/private/var/folders/lf/cjtf6ppx32b28hyzg6dgfnw1h6d7q3/T/RtmpCtvfyY/Rinst14ea3c8c2a63/liger'
E>       -----------------------------------
E> ERROR: package installation failed

**Comment by Akriebs** [comment]
Hi Shila,
Has the Mac User downloaded RcppArmadillo?

**Comment by shazanfar** [comment]
Hi April,

Thanks for this. The other mac user seems to have some unrelated issue with RcppArmadillo not specific to the liger package, and my download/install issue was solved by setting a longer timeout option
> options(timeout = 600)

I noticed (with a new example dataset) an error when the second dataset contains features that are a strict subset of the first dataset. This error is gone when you provide the subsetted dataset first, as below.

Cheers,
Shila

> counts_list = readRDS(file = url("https://www.dropbox.com/s/t0eqqek127dcg13/counts_list_2.Rds?raw=1"))
> # create liger object
> data_liger = createLiger(counts_list)
[1] "Removing 10079 genes not expressed in referenceSCE."
[1] "Removing 215 genes not expressed in querySCE."
> 
> # normalise the data
> data_liger <- liger::normalize(data_liger)
> 
> # select features from the unshared set, from all data modalities
> # using parameter from vignette
> data_liger <- selectGenes(data_liger, unshared = TRUE, 
+                           unshared.datasets = as.list(seq_len(length(counts_list))),
+                           unshared.thresh = 0.4)
[1] "Selected 617 unshared features from referenceSCE Dataset"
[1] "Selected 0 unshared features from querySCE Dataset"
> 
> # rescale the data
> data_liger <- scaleNotCenter(data_liger)
> 
> # perform the UINMF, using parameters from vignette
> data_liger <- optimizeALS(data_liger, k=30, use.unshared = TRUE)
[1] "Performing Factorization using UINMF"
[1] "Processing"
  |                                                                                                             |   0%Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 't': error in evaluating the argument 'x' in selecting a method for function 't': subscript out of bounds
> lapply(data_liger@scale.data, dim)
$referenceSCE
[1] 3611  971

$querySCE
[1] 6460  971

> lapply(data_liger@scale.unshared.data, dim)
$referenceSCE
[1]  617 3611

$querySCE
[1]    0 6460

# because the second dataset has a strict subset of features of the first dataset
# use only first data as the unshared dataset, as directed from function help
>     data_liger <- selectGenes(data_liger, unshared = TRUE,
+                               unshared.datasets = list(1),
+                               unshared.thresh = 0.4)
Error in names(unshared.feats) <- names(object@raw.data) : 
  'names' attribute [2] must be the same length as the vector [1]

**Comment by Akriebs** [comment]
Good afternoon Shila,
Again, thank you for your reproducible code and examples! Everything has been updated such that you shouldn't experience further issues after redownloading. Sorry for the hassle!
