### ISSUE TITLE
Way to write the UINMF Optimization

### ISSUE THREAD

**Issue by yjgeno** [welch-lab/liger#215]
Excellent work! 
Here I was just wondering if any specific reason to write UINMF as H*W, in the inverse order of standard NMF (which is W*H)?
For low-dimensional projection, did you use the columns of each H, the cell-factor matrices, instead of shared W?
Appreciate it if any help could be given. Thank you!

**Comment by Akriebs** [comment]
Hi,
Thank you for you inquiry. Both the original Liger algorithm (iNMF) and UINMF solve the same optimization equation. iNMF derivations, which can be found in the original publication, treat X as (n X m). UINMF solves the transpose (e.g, m x n). However the transpose of the frobenius norm is equivalent to the original forbenius norm, so it is the same optimization problem, with identical solutions (when there are no additional U features). It is just coded in a different way.  I can pass along the derivations if it would be beneficial. Both algorithms consequently use the columns of the H matrix (cell factor loadings) for the UMAP projections.
