### ISSUE TITLE
Error while running louvainCluster for scATAC + scRNA integration

### ISSUE THREAD

**Issue by KeyTals** [welch-lab/liger#217]
Hello,

I am getting following error which running clustering step. Some how the vector at "louvainCluster" step taking one less barcode then total rows in cell.data matrix.This is due to optimizeALS (if "scaleNotCenter" run with "remove.missing =FALSE", otherwise scaleNotCenter itsef) remove one cell(in this case) by giving "genes not expressing in atac" message . scale.data shows the correct number of cells after this but cell.data and other matrix still has all the cells inducing the removed one. 

 int <- louvainCluster(int, resolution = 0.6)
 
Louvain Clustering on quantile normalized cell factor loadings.
Error in names(clusts) <- rownames(object@cell.data) : 
  'names' attribute [101252] must be the same length as the vector [101251]

Thanks,
Keyur

**Comment by cgao90** [comment]
Hi Keyur, 

Thank you for trying out LIGER. Did you try `remove.missing = TRUE` (also by default) in `createLiger`? The cell.data matrix is generated at this step. If you disabled `remove.missing` at the beginning but enabled it later on in `scaleNotCenter`, it will cause discrepancy in the total number of cells.

**Comment by KeyTals** [comment]
Yes, i run with remove.missing = TRUE  first ,it was removing same number of cells at this step but even after cell.data was not reflecting the change.
I double checked the barcodes, scaleNotCenter and optimizeALS (if i ran previous with remove.missing = FALSE) were removing the same cells but in either case cell.data was not adjusted.

Keyur

**Comment by KeyTals** [comment]
Yes, cells are filtering out at scaleNotCenter(remove.missing = TRUE) or at scaleNotCenter(remove.missing = FALSE) + optimizeALS. 

here is the example 

int <- scaleNotCenter(int,remove.missing =TRUE)
Removing 1 genes not expressing in rna.
rna_TTCCTCTTCCGCAGTG-4

or 

> int <- scaleNotCenter(int,remove.missing =FALSE)
> int <- optimizeALS(int, k = 20)
Removing 1 genes not expressing in rna.
rna_TTCCTCTTCCGCAGTG-4


I am checking  if that cell has any variable genes expressed or not.

Keyur

**Comment by cgao90** [comment]
LIGER expects gene-by-cell matrices as input, could you also double check on this? Based on the message, it seems the barcodes are treated as genes.

**Comment by KeyTals** [comment]
Let me know of this is correct

>int@norm.data[[1]][10:15, 10:15]
6 x 6 sparse Matrix of class "dgCMatrix"
              atac_AAACGAAAGTTGACAA-6 atac_AAACGAACAAGCAACG-2 atac_AAACGAACACACGGTC-6
1700007L15Rik                       .             .                                 .
1700015F17Rik                       .             .                                 .
1700018M17Rik                       .             .                                 .
1700022N22Rik                       .             .                                 .
1700024J04Rik                       .             .                                 .
1700028P14Rik                       .             0.000103756                       .
              atac_AAACGAACATAGACGG-2 atac_AAACGAAGTACGTAGG-5 atac_AAACGAAGTACTAGAA-5
1700007L15Rik                       .                       .                       .
1700015F17Rik                       .                       .                       .
1700018M17Rik                       .                       .                       .
1700022N22Rik                       .                       .                       .
1700024J04Rik                       .                       .                       .
1700028P14Rik                       .                       .                       .
> 
> 
> int@norm.data[[2]][10:15, 10:15]
6 x 6 sparse Matrix of class "dgCMatrix"
              rna_AAACGAAAGCGGACAT-1 rna_AAACGAAAGGTAGCCA-1 rna_AAACGAACACAGCTTA-1
Rgs20                              .                      .            .          
Atp6v1h                            .                      .            .          
Oprk1                              .                      .            .          
Rb1cc1                             .                      .            0.002202643
4732440D04Rik                      .                      .            .          
St18                               .                      .            .          
              rna_AAACGAAGTCGACTTA-1 rna_AAACGAAGTGGTAATA-1 rna_AAACGAAGTTAAGGGC-1
Rgs20                              .           .                                 .
Atp6v1h                            .           .                                 .
Oprk1                              .           .                                 .
Rb1cc1                             .           0.0007830854                      .
4732440D04Rik                      .           .                                 .
St18                

both RNA and ATAC are in same format.

**Comment by cgao90** [comment]
Yes, they are correct. "Removing 1 genes not expressing in rna." should be "Removing 1 cell not expressing in rna." due to a minor issue in the source code. Sorry about the confusion.
