### ISSUE TITLE
Is there python version for Liger

### ISSUE THREAD

**Issue by ChineseBest** [welch-lab/liger#219]
It seems that there is no python API for Liger, is there anyone can tell me where I can find a similar use? Thanks

**Comment by skpalan** [comment]
Hi, we definitely understand the needs of python users. In this stage, the python version of LIGER is still under development. It will be released in near future. Thank you!

**Comment by ChineseBest** [comment]
OK, sad. In addition, could you please give me some hints about how to design the API from python data to R data? Thanks

**Comment by skpalan** [comment]
LIGER takes two kinds of data as inputs, **gene by cell matrices** (both sparse and dense) and **hdf5 files**. Regradless of what python data structures you are using, you can always convert them into these two formats and then pass to R and LIGER.

**Comment by ChineseBest** [comment]
Could I input the np.array file to liger model? Do you have any tutorial documents related to this part? Thanks a lot. I've been struggling with this problem for a long time. Thanks a lot.
