### ISSUE TITLE
rename clusters to celltypes

### ISSUE THREAD

**Issue by deevdevil88** [welch-lab/liger#220]
Hi ,
is there a way to rename the clusters variable to celltypes manually ? can i just rename the factor  and will that work?

Thanks
Devika

**Comment by skpalan** [comment]
Of course! The `@clusters` slot of a LIGER object stores a typical R `factor` object, you can make any modifications you prefer. Just be aware that the `names` of the `@clusters` slot should correpond to the barcodes of the input datasets stored in `@raw.data` and `@norm.data` slots.
