### ISSUE TITLE
Invalid character indexing when preparing dataset for projection

### ISSUE THREAD

**Issue by fbrundu** [welch-lab/liger#222]
Hi,

I am having trouble working on scenario 3 of [Iterative single-cell multi-omic integration using online learning](http://htmlpreview.github.io/?https://github.com/welch-lab/liger/blob/master/vignettes/online_iNMF_tutorial.html)

I am testing a setup where I first integrate WT samples and then project Mutant samples. However, during scaling of the mutant samples I get the following error:

```
> mut.ldata <- scaleNotCenter(mut.ldata)
Error in intI(i, n = x@Dim[1], dn[[1]], give.dn = FALSE) : 
  invalid character indexing
```

I tested and both WT and Mutant have the same genes in the raw data. An excerpt of the code is the following:

```
# wt.sdata and mut.sdata are Seurat objects for WT and Mutant samples

wt.ldata <- liger::seuratToLiger(wt.sdata, combined.seurat=T, meta.var='batch')
rm(wt.sdata)

mut.ldata <- liger::seuratToLiger(
    mut.sdata, combined.seurat=T, meta.var='batch',
)
rm(mut.sdata)

wt.ldata <- normalize(wt.ldata)
wt.ldata <- selectGenes(wt.ldata)
wt.ldata <- scaleNotCenter(wt.ldata)

mut.ldata <- normalize(mut.ldata)
mut.ldata@var.genes <- wt.ldata@var.genes
mut.ldata <- scaleNotCenter(mut.ldata)
```

What are other things that I can test to troubleshoot this issue? I am running the latest Liger version from github.

Thanks,
Francesco

**Comment by cgao90** [comment]
Hi Francesco,

Thanks for trying out LIGER. When you were checking the genes in the raw data, are they the data matrices stored in the `raw.data` (or `norm.data`, either is fine) slot in `wt.ldata` or `mut.ldata` objects? Could you also try extracting the `wt.ldata@var.genes` and manually check if they are included in the rownames(mut.ldata@norm.data[[i]])?

Best,
Chao

**Comment by fbrundu** [comment]
Thanks! You're right, few are not all included in some mutant samples:

```
> length(wt.ldata@var.genes)
[1] 11618
> length(intersect(wt.ldata@var.genes, rownames(mut.ldata@norm.data$mut1)))
[1] 11616
> length(intersect(wt.ldata@var.genes, rownames(mut.ldata@norm.data$mut2)))
[1] 11605
> length(intersect(wt.ldata@var.genes, rownames(mut.ldata@norm.data$mut3)))
[1] 11615
> length(intersect(wt.ldata@var.genes, rownames(mut.ldata@norm.data$mut4)))
[1] 11603
> length(intersect(wt.ldata@var.genes, rownames(mut.ldata@norm.data$mut5)))
[1] 11601
> length(intersect(wt.ldata@var.genes, rownames(mut.ldata@norm.data$mut6)))
[1] 11617
> length(intersect(wt.ldata@var.genes, rownames(mut.ldata@norm.data$mut7)))
[1] 11613
> length(intersect(wt.ldata@var.genes, rownames(mut.ldata@norm.data$mut8)))
[1] 11604
```

I guess the best solution, in this case, would be to remove from `wt.ldata@var.genes` the few genes that are not present in all the mutant samples. Ideally, with such a low number of missing genes, the probability of removing an interesting gene is probably acceptable?
And, however, their expression would need to be imputed otherwise, in the samples where they are missing.
Is there another way, e.g. through LIGER, that I didn't consider?

Thanks

**Comment by cgao90** [comment]
Let's first try removing those genes not shared across all datasets. Also, 10k+ variable genes will slow down the computation. 2000 variable genes (by tuning var.thresh parameter in the `selectGenes`) would work in many cases.
