### ISSUE TITLE
KL divergence is not plateauing

### ISSUE THREAD

**Issue by nfancy** [welch-lab/liger#229]
Hi 

Thanks for developing this great package. For one of my dataset, I was trying suggestk and even after trying a K of up to 100, the KL divergence slope is not plateauing. Is this expected? My dataset is a really large one. 350k nuclei 87 samples. The plot is attached.

![liger_k_5_100](https://user-images.githubusercontent.com/50167573/122562164-aaf81e00-d03a-11eb-8704-8ab8dbc35e99.png)

**Comment by cgao90** [comment]
Hi, 

`suggestK` serves as a heuristic and it is possible that there is no obvious plateau (Just like we may not find the optimal "elbow" in a Scree plot for PCA.). You could try continuing the analysis with a few choices of K (base on the prior knowledge about the complexity of the data) and compare the integration results, and then decide on a proper K.

**Comment by LeoCao-X** [comment]
Thanks for your reply! I will try to test some k values manually.

**Comment by nfancy** [comment]
Hi, Thank you very much. Do you have a suggested range for K?

Thanks.

**Comment by cgao90** [comment]
Hi, 20-50 would work for many cases.
