### ISSUE TITLE
Dose it have any effect on optimizeALS if the scale.data have negative values？

### ISSUE THREAD

**Issue by WellJoea** [welch-lab/liger#232]
What are  the effects on optimizeALS If the scale.data  with negative values are scaled by ScaleData(do.center = FALSE) after CCA batch?
When using liger to integrate multi-species, the batches in each species cannot be removed. 
So, if CCA is used for correcting the batches in each species among samples and then use the CCA matrix with negative value as the input of optimizeALS, Is there any effect on final result？

**Comment by jw156605** [comment]
liger will essentially treat any negative values as 0 if you try to run optimizeALS. I do not recommend doing this.

**Comment by WellJoea** [comment]
I see! Thank you very much!
