### ISSUE TITLE
How to format data as .h5 file?

### ISSUE THREAD

**Issue by smorabit** [welch-lab/liger#233]
Hi,

I am interested in using the Scenario 2 (iterative refinement) of online iNMF to integrate a bunch of different single-cell datasets. For each dataset I have the counts matrix as a .mtx file, and I have cell metadata as a .csv. I am not sure how I am supposed to create a .h5 file that can be read by liger using this information, and it does not seem like there is any tutorial that I can find that goes over this topic. Any help would be greatly appreciated. Online iNMF scenario 1 does work if I load into memory but it seems like scenario 2 requires .h5 files, and I would prefer to use the .h5 approach anyways so I can scale up to include more datasets.

Cheers,

Sam

**Comment by samuel-marsh** [comment]
Hi Sam,

Not dev team but one way to do it is to use DropletUtils package and the `write10xCounts` function which can turn any count matrix into a 10X formatted h5 file which can then be read in by liger (or Seurat).

Best,
Sam

**Comment by cgao90** [comment]
In addition to Sam's solution, you could also check out this previous discussion (#211 ) if you want to manually create a h5 file.
