### ISSUE TITLE
How to include unshared features other than genes when doing uINMF?

### ISSUE THREAD

**Issue by sheetalgiri** [welch-lab/liger#234]
I'm interested in reproducing the results for integrating scRNA and snATAC data from the paper.  With the standard liger, I'm converting the snATAC data to gene activity data since we can't do further processing without it.  So, I'm a bit confused about how we can include the intergenic peak data as a feature.

**Comment by Akriebs** [comment]
We use a gene-centric matrix for the shared features between data sets. For the intergenic regions, we bin the genome, and remove bins that overlap genes and known promoter regions. We then use the peaks present in each remaining bin as  our unshared features. If you would like to walk through the analysis in a little more depth, we just uploaded a vignette that walks through the analysis in the paper in a little more detail (http://htmlpreview.github.io/?https://github.com/welch-lab/liger/blob/master/vignettes/SNAREseq_walkthrough.html ). Please let us know if you have any further questions!
