### ISSUE TITLE
optimizeALS fails due to high CPU requirements

### ISSUE THREAD

**Issue by nfancy** [welch-lab/liger#235]
Hi,

I've recently upgraded to rliger 1.0.0 and noticing that many of my job on HPC are failing due to exceeding the cpu requirement even with not so large dataset which ran fine with the previous version. The job is failing at optimizeALS step. Any pointers is hugely appreciated. Thanks.

Nurun

**Comment by skpalan** [comment]
Hi Nurun, can you provide more information of the job failure on HPC? For exmaple, the size of the dataset, the resources (CPU, RAM, etc.) requested for the job. For version 1.0.0, we barely modified codes of the function `optimizeALS` so it could be due to other reasons.
