### ISSUE TITLE
Data download link for scRNA-seq + scATAC-seq integration tutorial seems to have expired

### ISSUE THREAD

**Issue by Jeff1995** [welch-lab/liger#240]
Hi LIGER team!

I just noticed that the data download link
https://umich.box.com/s/wip2nzpktn6fdnlpc83o1u7anjn4ue2c
on the scRNA-seq and scATAC-seq integration turorial
http://htmlpreview.github.io/?https://github.com/welch-lab/liger/blob/master/vignettes/Integrating_scRNA_and_scATAC_data.html
seems to have expired.

It says "This shared file or folder link has been removed or is unavailable to you".
It would be great if these links can be updated.

Also, the link for the archived tutorials, e.g.,
https://macoskolab.github.io/liger/walkthrough_rna_atac.html
might also need update to
https://welch-lab.github.io/liger/walkthrough_rna_atac.html

**Comment by eijynagai** [comment]
Hi,
Thank you very much for creating such an amazing tool! 

I am not familiar with NMF, so I would like to test the online iNMF tool following the tutorial first before using it on my own data. 
I noticed that the link you provided to download `pbmcs_stim.h5` is not working. Could you please fix the link? =)

**Comment by cgao90** [comment]
Hi Eijy,

Sorry about the inconvenience. The link has now been fixed.

Best,
Chao

**Comment by eijynagai** [comment]
Hey Chao, 

Thank you so very much for your quick fix!
Now the link is working! 

Best regards,

Eijy
