### ISSUE TITLE
scaleNotCenter error in online_iNMF method

### ISSUE THREAD

**Issue by niehu2018** [welch-lab/liger#243]
suppressPackageStartupMessages({
  library(rliger)
  library(dplyr)
  library(ggplot2)
})

###read data
readData <- function(sampleName, filePath, remove.missing = TRUE, meta.var = NULL){
  seu_list <- list()
  for(i in 1:length(sampleName)){
    sample <- sampleName[i]
    path <- filePath[i]
    cat(i, sample, path, "\n")
    seu_list[[i]] <- readRDS(path)
  }
  names(seu_list) <- sampleName
  
  liger <- seuratToLiger(seu_list, names = sampleName, meta.var = meta.var, raw.assay	= 'RNA', remove.missing = remove.missing)
  rm(seu_list)
  return(liger)
}

part1_data_info <- infiles[part1, ]
liger <- readData(part1_data_info$name, part1_data_info$path)

####input data
liger <- normalize(liger)
liger <- selectGenes(liger, var.thresh = 0.3, do.plot = F)
liger@var.genes %>% length
liger <- scaleNotCenter(liger)
liger <- online_iNMF(liger, k = 20, miniBatch_size = 5000, max.epochs = 5)
liger <- quantile_norm(liger)
liger <- runUMAP(liger)

part2_data_info <- infiles[part2, ]
liger_part2 <- readData(part2_data_info$name, part2_data_info$path)

liger_part2 <- normalize(liger_part2)
liger_part2@var.genes <- liger@var.genes
liger_part2 <- scaleNotCenter(liger_part2)
**Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 't': invalid character indexing**

If I set remove.missing = F in seuratToLiger function, this error do not occure.
It seems that the var.genes in liger_part1 do not exist in liger_part2 genes!
What should I do to fix this problem?

**Comment by cgao90** [comment]
Hi, Thanks for trying out liger! Could you try subset the input datasets using the genes that are shared across all different parts?
