### ISSUE TITLE
Data download link seems invalid

### ISSUE THREAD

**Issue by GuangshengZ** [welch-lab/liger#248]
Hi,
Thanks for your great work! I have noticed that the download link of Integrating Multiple Single-Cell RNA-seq Datasets https://umich.app.box.com/s/n1xfpu9hplrknu6to6u9kvbktsqcql8t seems invalid. It says "This shared file or folder link has been removed or is unavailable to you". Neither are the links in Jointly Defining Cell Types from scRNA-seq and scATAC-seq https://umich.box.com/s/wip2nzpktn6fdnlpc83o1u7anjn4ue2c or Jointly Defining Cell Types from Single-Cell RNA-seq and DNA Methylation https://umich.box.com/s/atkmkx37ersh55whlu1zn63yd1eg3wst. It would be great if these links can be updated. Thanks!

Guangsheng

**Comment by skpalan** [comment]
Hi Guangsheng, we have updated the links to the example data. Thanks!

**Comment by ssun1116** [comment]
Hello, it seems like the download link for "jointly Defining Cell Types from Single-Cell RNA-seq and DNA Methylation https://umich.box.com/s/atkmkx37ersh55whlu1zn63yd1eg3wst" is still not valid. Could you please check if this can be updated? Thanks a lot.
