### ISSUE TITLE
get batch corrected matrix from Seurat object 

### ISSUE THREAD

**Issue by ceesu** [welch-lab/liger#249]
Hello there, thanks for your package. I have the latest version of the following libraries:
```
library(rliger)
library(Seurat)
library(SeuratWrappers)
```

 I used the wrapper from [here](https://github.com/satijalab/seurat-wrappers/blob/master/docs/liger.md) to run liger on a Seurat object for batch correction. However, after the step `RunQuantileNorm`, I am not sure how to get the batch corrected expression matrix. 

I found the slots "iNMF" and "iNMF_raw" in the Seurat object but these are in terms of the NMF components. It seems like for liger objects we can access the corrected H.norm after running `quantile_norm`, can we also do something like this for Seurat objects?

**Comment by mvfki** [comment]
Liger integrates datasets via iNMF approach, which tries to align the factorized cell factor loading in the NMF component space. So no batch corrected gene expression matrix would be generated.

**Comment by mvfki** [comment]
The reduction object "iNMF" is H.norm by the way.
