### ISSUE TITLE
strange behavior with selectGenes() for UINMF

### ISSUE THREAD

**Issue by schroeme** [welch-lab/liger#250]
Hi, we are using LIGER-UINMF to integrate snRNAseq data across species. We have found that no matter how low we make the unshared.thresh variable, no unshared genes are identified unless unshared.thresh is lower than shared.thresh. Furthermore, the same number of unshared genes are identified regardless of the value of unshared.thresh. Shouldn't the two thresholds be independent of one another, and shouldn't more unshared variable genes be identified with a lower unshared.thresh value?

**Comment by Akriebs** [comment]
Hi schroeme,
Thank you for reaching out. One quick note is that the updated UINMF algorithm has been added to the regular rliger package, so I would recommend updating your rliger version, and using that to run UINMF if you have not already done so. We updated the select genes function in this newest version, so this may alleviate your problem. If not, please let us know, and we can continue to help you debug!

**Comment by Akriebs** [comment]
I will close this issue for now, but feel free to reach out with further inquiries if the problem persists.
