### ISSUE TITLE
selectGenes No genes were selected

### ISSUE THREAD

**Issue by scarlettcanny0629** [welch-lab/liger#258]
Hi,

The selectGenes function is always reporting   No genes were selected; lower var.thresh values or choose 'union' for combine parameter even with var.thresh= 0 threshold and union for combine parameter.

And the confusing thing is that when I set do.plot =T I can see that there are thousands of genes being selected.

I am wondering the issue causing this problem, thanks
![selectgenes](https://user-images.githubusercontent.com/83673835/159532450-1572a004-1136-4f81-ac42-9b343250668c.png)
!

**Comment by mvfki** [comment]
We have updated rliger quite a lot in new version 2.0. There are fixes happening in `selectGenes()`. I'm closing this Issue for now because it corresponds to a pretty old version. Please feel free to reopen it if you try the new rliger and still encounter this issue.
