### ISSUE TITLE
Error in scaleNotCenterFast(t(object@norm.data[[i]][object@var.genes,  :    Not an S4 object.

### ISSUE THREAD

**Issue by Muchmorepig** [welch-lab/liger#261]
when I analyzed my own data following: http://htmlpreview.github.io/?https://github.com/welch-lab/liger/blob/master/vignettes/Integrating_scRNA_and_scATAC_data.html

I met a problem: **Error in scaleNotCenterFast(t(object@norm.data[[i]][object@var.genes,  :    Not an S4 object**, when run `scaleNotCenter(int_cim22d)` 

here is my code:
```R
int_cim22d <- rliger::normalize(int_cim22d)

int_cim22d <- selectGenes(int_cim22d,
    datasets.use = 2,
    var.thresh = 0.05
    # combine = "intersection"
)

int_cim22d <- scaleNotCenter(int_cim22d)

packageVersion("rliger")                                                      
# [1] ‘1.0.0’
# R : 4.1
```
can anyone help me?

**Comment by Cumol** [comment]
@Muchmorepig how did you solve this issue?
