### ISSUE TITLE
How to transfer cell labels from one dataset to another dataset?

### ISSUE THREAD

**Issue by Telogen** [welch-lab/liger#262]
Hi team! I see LIGER can successfully integrate two single-cell datasets. I wonder if the cell types of one dataset are known, how to transfer cell labels from one dataset to another? Is it possible to use LIGER to do this like what `TransferData()` do in Seurat. Many thanks!

**Comment by cgao90** [comment]
Hi, Thank you for checking out LIGER. At this moment, LIGER does not have a function that directly carries out cell label transfer. Instead, you could try projecting a new dataset into the latent space inferred by previous integration (Scenario 3 in this tutorial: http://htmlpreview.github.io/?https://github.com/welch-lab/liger/blob/master/vignettes/online_iNMF_tutorial.html), then run `quantile_norm` and  `louvainCluster`. Once you obtain the clusters, you could annotate the cells from the new dataset based on labeled cells in the same cluster.

**Comment by Telogen** [comment]
Thanks for your answering!
