### ISSUE TITLE
Vignettes for 10x Multiome data?

### ISSUE THREAD

**Issue by tanlongzhi** [welch-lab/liger#266]
Hi LIGER dev team,

We really enjoyed your package, but wonder if there're examples/tutorials for integrating multiple runs of 10x Multiome data? Thank you very much!

By the way, may I ask where the files "hg19_genes.bed" and "hg19_promoters.bed" come from in the current tutorials? Were they outputs from 10x Cell Ranger? We don't have them from the 10x Multiome pipeline.

Best,
Tan

**Comment by cgao90** [comment]
Hi Tan,

Thank you for trying out LIGER. At the moment, LIGER doesn't support integrating single-cell multimodal data (e.g. 10x Multiome). 

These bed files are not outputs from the cell ranger, and you could generate them yourself (e.g. in R). They are essentially the coordinates of each gene/promoter. There are a few related discussions (genes: https://www.biostars.org/p/427912/ , promoters: https://www.biostars.org/p/8207/). 

Best,

**Comment by tanlongzhi** [comment]
Thank you @cgao90 very much for the prompt help and detailed reply! It's super informative.

Best,
Tan

**Comment by jshi7** [comment]
Hi LIGER team, 

Do you by any chance have the hg38 promoter and gene bed files?

Thank you!
Jenny

**Comment by cgao90** [comment]
Hi @jshi7 ,

Here are two example hg38 promoter and gene bed files you can try (https://www.dropbox.com/sh/tkky33qd6fu6a4n/AAAVsSDYJZJj2vqu0J1UsVmya?dl=0). MT genes are not included.

Best,
Chao
