### ISSUE TITLE
Subsetting integrated seurat object and reclustering using liger

### ISSUE THREAD

**Issue by Prathyusha-konda** [welch-lab/liger#276]
Hi, I have an integrated seurat object from 6 datasets from which I want to subset specific clusters and recluster using liger. I would like to know if there is a recommended workflow for this. 

Should I split the integrated seurat and rerun the entire pipeline? (from this tutorial - https://htmlpreview.github.io/?https://github.com/satijalab/seurat.wrappers/blob/master/docs/liger.html)

Does it matter if the seurat object was originally integrated with liger or logNormalize or SCT?

Thanks in advance for your suggestions!

ifnb <- NormalizeData(ifnb)
ifnb <- FindVariableFeatures(ifnb)
ifnb <- ScaleData(ifnb, split.by = "stim", do.center = FALSE)
ifnb <- RunOptimizeALS(ifnb, k = 20, lambda = 5, split.by = "stim")
ifnb <- RunQuantileNorm(ifnb, split.by = "stim")
ifnb <- FindNeighbors(ifnb, reduction = "iNMF", dims = 1:20)
ifnb <- FindClusters(ifnb, resolution = 0.55)
ifnb <- RunUMAP(ifnb, dims = 1:ncol(ifnb[["iNMF"]]), reduction = "iNMF")

**Comment by cgao90** [comment]
Hi, we would suggest subsetting the cells in the clusters of interest and running the entire LIGER pipeline (start with the count data).
