### ISSUE TITLE
Lowest suggested value for lambda?

### ISSUE THREAD

**Issue by lucygarner** [welch-lab/liger#279]
Hi,

Is there a minimum value that you suggest for lambda? I tested from 5 down to 0.001 using `RunOptimizeALS` from `SeuratWrappers` and it didn't seem to affect the integration much.

Best wishes,
Lucy

**Comment by cgao90** [comment]
Hi Lucy, 

In most cases, lambda doesn't have a significant impact on `RunOptimizeALS`. Normally we set `lambda = 5` by default in analyses. When it comes to online iNMF, it can have a larger effect at times. 

Best,
