### ISSUE TITLE
"shared factor neighborhood" not used anymore as described in the paper?

### ISSUE THREAD

**Issue by ccshao** [welch-lab/liger#280]
Hi liger team. 

Many thanks for this nice toolsets!  

When I went through the methods parts of liger paper, the joint clustering is performed on the basis of shared factor neighborhood, e.g., get the factor neighborhood and calculate the Manhattan distance. However, it seems not to be the case anymore in the current implementation. Instead, it looks to me that Louvain community detection is performed on graphs built with knn on quantile normalized H matrix. 

Did I misunderstood something? Details on the changes and implementations are appreciated, thanks a lot!

**Comment by cgao90** [comment]
Hi, the LIGER team have been actively incorporate new functions and features into the package. You are right about the original LIGER paper. The quantile normalization + Louvain method strategy was introduced afterwards along with online iNMF.

**Comment by ccshao** [comment]
Thanks for the clarification, sorry I didn't notice the updates on the online algorithm.

**Comment by jw156605** [comment]
The new algorithm is thoroughly described in the method section of our Nature Biotechnology paper (Gao et al 2021).
________________________________
