### ISSUE TITLE
cran package archived

### ISSUE THREAD

**Issue by nfancy** [welch-lab/liger#293]
Hi,

Perhaps you've notified already. Cran archived rliger as riverplot package is archived.

BW
Nurun

**Comment by samuel-marsh** [comment]
Hi LIGER team,

Is there a timeline for a fix on this?  I have package which suggests rliger (not even hard depend) and is failing CRAN checks because of rliger not on CRAN.  Timely fix would be greatly appreciated!

Thanks,
Sam

**Comment by jw156605** [comment]
We have submitted the update to CRAN and are fighting through approval now. Sorry for the inconvenience! We'll have it fixed soon.
**********************************************************
Electronic Mail is not secure, may not be read every day, and should not be used for urgent or sensitive issues

**Comment by samuel-marsh** [comment]
Fantastic!  Thanks so much and thanks for quick reply!!

**Comment by mvfki** [comment]
@samuel-marsh It's back! Thanks for your patience!

**Comment by samuel-marsh** [comment]
@mvfki Awesome thanks so much!  Hope to push scCustomize to CRAN by end of this week.  Wrapping up testing of Seurat5 comptability and then will test against new liger version (just to be safe).

Best,
Sam

**Comment by mvfki** [comment]
There are not too many changes. We are just commenting out one function where the dependency (riverplot) became unavailable. And as per CRAN policy, we spent most of the time fixing Rd doc issues.
