### ISSUE TITLE
no slot name "defaultCluster" for this object of class "liger"

### ISSUE THREAD

**Issue by Obtusah** [welch-lab/liger#310]
Hi, while running a code using liger package,
The error seems to be caused of liger object. My  
```
object@uns
```
doesn't have attribute 'defaultCluster'. 
I printed out the 'object@uns'. The contents were lines below "+++...++" in the image.
only attributes named factorization and factorization$k were present.

I searched liger code and am guessing 'defaultCluster' is some kind of getter. 

![image](https://github.com/welch-lab/liger/assets/93822301/77395e3d-1422-496e-9219-a6118038bf4f)

**Comment by mvfki** [comment]
Hi @Obtusah ,

`defaultCluster` is technically not a "slot" in R terms. You'll be able to access it with getter function `defaultCluster(sr_liger)` once you have it set. From the screenshot, it doesn't seem that you have any clustering result present at this moment, so you should get `NULL` when you call that getter. It'll be automatically set when you have your first clustering run. If you need to tweak parameters and save an alternative result with a different variable name, you might need to reset with `defaultCluster(sr_liger) <- <newVariable>`. If you really need to use symbol access like `@`, it is accessible at `sr_liger@uns$defaultCluster`. Note that `defaultDimRed` is accessed in a similar way.

Best,
Yichen
