### ISSUE TITLE
I cannot find joint cluster result in liger object

### ISSUE THREAD

**Issue by DruncBread** [welch-lab/liger#316]
Hi,
How can I find the joint cluster result?
I integrated a ATAC data with 2129 cells and a RNA data with 2129 cells, but I can only find leiden_cluster with 4258 cells.
I hope to find the joint cluster result which should be a 2129*1 list.
Thanks!

**Comment by mvfki** [comment]
Hi,
Are the ATAC and RNA data from the same set of cells i.e. multimodal data? If so, liger is not the method for the purpose.

**Comment by DruncBread** [comment]
I see. thank you!
